### ISSUE TITLE
Статус PROCESSING

### ISSUE THREAD

**Issue by akobabkov** [codus-dev/FNSApi#4]
Приветствую. Прошерстил все документации какие смог найти, в оф документации нет ответа. Не могу найти инфу о статусе PROCESSING, что он значит? Это значит, что данные еще не обработаны и стоит запросить позже или что? Как с ним работать?

**Comment by MarkKhromov** [comment]
> Приветствую. Прошерстил все документации какие смог найти, в оф документации нет ответа. Не могу найти инфу о статусе PROCESSING, что он значит? Это значит, что данные еще не обработаны и стоит запросить позже или что? Как с ним работать?

Привет! Да, это значит, что со стороны налоговой не поступил ответ полноценный, он только в очереди на обработку и запрос нужно повторить немного позже. Пока не придёт статус COMPLETED.
